### ISSUE TITLE
Multistore

### ISSUE THREAD

**Issue by SajRus** [PrestaShop/ps_imageslider#44] opened 2019-08-20 06:56 UTC
the module does not support multistore option, everything think (image, text) you change in one store will bee propagated on the other stores.

**Comment by khouloudbelguith** [comment] 2019-08-20 09:25
Hi @SajRus,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9710
So, I close it.
Thanks!

**Closed by khouloudbelguith** 2019-08-20 09:25 UTC
